// Mocks generated by Mockito 5.4.6 from annotations
// in interactive_media_ads/test/android/ads_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:interactive_media_ads/src/android/interactive_media_ads.g.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePigeonInstanceManager_0 extends _i1.SmartFake implements _i2.PigeonInstanceManager {
  _FakePigeonInstanceManager_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFrameLayout_1 extends _i1.SmartFake implements _i2.FrameLayout {
  _FakeFrameLayout_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeMediaPlayer_2 extends _i1.SmartFake implements _i2.MediaPlayer {
  _FakeMediaPlayer_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeVideoAdPlayer_3 extends _i1.SmartFake implements _i2.VideoAdPlayer {
  _FakeVideoAdPlayer_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVideoView_4 extends _i1.SmartFake implements _i2.VideoView {
  _FakeVideoView_4(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeAdError_5 extends _i1.SmartFake implements _i2.AdError {
  _FakeAdError_5(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeAdErrorEvent_6 extends _i1.SmartFake implements _i2.AdErrorEvent {
  _FakeAdErrorEvent_6(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeAdErrorListener_7 extends _i1.SmartFake implements _i2.AdErrorListener {
  _FakeAdErrorListener_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdEvent_8 extends _i1.SmartFake implements _i2.AdEvent {
  _FakeAdEvent_8(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeAdEventListener_9 extends _i1.SmartFake implements _i2.AdEventListener {
  _FakeAdEventListener_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdsManager_10 extends _i1.SmartFake implements _i2.AdsManager {
  _FakeAdsManager_10(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeAdsRenderingSettings_11 extends _i1.SmartFake implements _i2.AdsRenderingSettings {
  _FakeAdsRenderingSettings_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCompanionAdSlot_12 extends _i1.SmartFake implements _i2.CompanionAdSlot {
  _FakeCompanionAdSlot_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeImaSdkSettings_13 extends _i1.SmartFake implements _i2.ImaSdkSettings {
  _FakeImaSdkSettings_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdsLoader_14 extends _i1.SmartFake implements _i2.AdsLoader {
  _FakeAdsLoader_14(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeAdsRequest_15 extends _i1.SmartFake implements _i2.AdsRequest {
  _FakeAdsRequest_15(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeImaSdkFactory_16 extends _i1.SmartFake implements _i2.ImaSdkFactory {
  _FakeImaSdkFactory_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FrameLayout].
///
/// See the documentation for Mockito's code generation for more information.
class MockFrameLayout extends _i1.Mock implements _i2.FrameLayout {
  @override
  _i2.PigeonInstanceManager get pigeon_instanceManager =>
      (super.noSuchMethod(
            Invocation.getter(#pigeon_instanceManager),
            returnValue: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
            returnValueForMissingStub: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
          )
          as _i2.PigeonInstanceManager);

  @override
  _i2.FrameLayout pigeon_copy() =>
      (super.noSuchMethod(
            Invocation.method(#pigeon_copy, []),
            returnValue: _FakeFrameLayout_1(this, Invocation.method(#pigeon_copy, [])),
            returnValueForMissingStub: _FakeFrameLayout_1(
              this,
              Invocation.method(#pigeon_copy, []),
            ),
          )
          as _i2.FrameLayout);

  @override
  _i3.Future<void> addView(_i2.View? view) =>
      (super.noSuchMethod(
            Invocation.method(#addView, [view]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeView(_i2.View? view) =>
      (super.noSuchMethod(
            Invocation.method(#removeView, [view]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [MediaPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaPlayer extends _i1.Mock implements _i2.MediaPlayer {
  @override
  _i2.PigeonInstanceManager get pigeon_instanceManager =>
      (super.noSuchMethod(
            Invocation.getter(#pigeon_instanceManager),
            returnValue: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
            returnValueForMissingStub: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
          )
          as _i2.PigeonInstanceManager);

  @override
  _i3.Future<int> getDuration() =>
      (super.noSuchMethod(
            Invocation.method(#getDuration, []),
            returnValue: _i3.Future<int>.value(0),
            returnValueForMissingStub: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> seekTo(int? mSec) =>
      (super.noSuchMethod(
            Invocation.method(#seekTo, [mSec]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setVolume(double? leftVolume, double? rightVolume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [leftVolume, rightVolume]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i2.MediaPlayer pigeon_copy() =>
      (super.noSuchMethod(
            Invocation.method(#pigeon_copy, []),
            returnValue: _FakeMediaPlayer_2(this, Invocation.method(#pigeon_copy, [])),
            returnValueForMissingStub: _FakeMediaPlayer_2(
              this,
              Invocation.method(#pigeon_copy, []),
            ),
          )
          as _i2.MediaPlayer);
}

/// A class which mocks [VideoAdPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoAdPlayer extends _i1.Mock implements _i2.VideoAdPlayer {
  @override
  void Function(_i2.VideoAdPlayer, _i2.VideoAdPlayerCallback) get addCallback =>
      (super.noSuchMethod(
            Invocation.getter(#addCallback),
            returnValue: (_i2.VideoAdPlayer pigeon_instance, _i2.VideoAdPlayerCallback callback) {},
            returnValueForMissingStub:
                (_i2.VideoAdPlayer pigeon_instance, _i2.VideoAdPlayerCallback callback) {},
          )
          as void Function(_i2.VideoAdPlayer, _i2.VideoAdPlayerCallback));

  @override
  void Function(_i2.VideoAdPlayer, _i2.AdMediaInfo, _i2.AdPodInfo) get loadAd =>
      (super.noSuchMethod(
            Invocation.getter(#loadAd),
            returnValue:
                (
                  _i2.VideoAdPlayer pigeon_instance,
                  _i2.AdMediaInfo adMediaInfo,
                  _i2.AdPodInfo adPodInfo,
                ) {},
            returnValueForMissingStub:
                (
                  _i2.VideoAdPlayer pigeon_instance,
                  _i2.AdMediaInfo adMediaInfo,
                  _i2.AdPodInfo adPodInfo,
                ) {},
          )
          as void Function(_i2.VideoAdPlayer, _i2.AdMediaInfo, _i2.AdPodInfo));

  @override
  _i3.Future<void> Function(_i2.VideoAdPlayer, _i2.AdMediaInfo) get pauseAd =>
      (super.noSuchMethod(
            Invocation.getter(#pauseAd),
            returnValue: (_i2.VideoAdPlayer pigeon_instance, _i2.AdMediaInfo adMediaInfo) =>
                _i3.Future<void>.value(),
            returnValueForMissingStub:
                (_i2.VideoAdPlayer pigeon_instance, _i2.AdMediaInfo adMediaInfo) =>
                    _i3.Future<void>.value(),
          )
          as _i3.Future<void> Function(_i2.VideoAdPlayer, _i2.AdMediaInfo));

  @override
  void Function(_i2.VideoAdPlayer, _i2.AdMediaInfo) get playAd =>
      (super.noSuchMethod(
            Invocation.getter(#playAd),
            returnValue: (_i2.VideoAdPlayer pigeon_instance, _i2.AdMediaInfo adMediaInfo) {},
            returnValueForMissingStub:
                (_i2.VideoAdPlayer pigeon_instance, _i2.AdMediaInfo adMediaInfo) {},
          )
          as void Function(_i2.VideoAdPlayer, _i2.AdMediaInfo));

  @override
  void Function(_i2.VideoAdPlayer) get release =>
      (super.noSuchMethod(
            Invocation.getter(#release),
            returnValue: (_i2.VideoAdPlayer pigeon_instance) {},
            returnValueForMissingStub: (_i2.VideoAdPlayer pigeon_instance) {},
          )
          as void Function(_i2.VideoAdPlayer));

  @override
  void Function(_i2.VideoAdPlayer, _i2.VideoAdPlayerCallback) get removeCallback =>
      (super.noSuchMethod(
            Invocation.getter(#removeCallback),
            returnValue: (_i2.VideoAdPlayer pigeon_instance, _i2.VideoAdPlayerCallback callback) {},
            returnValueForMissingStub:
                (_i2.VideoAdPlayer pigeon_instance, _i2.VideoAdPlayerCallback callback) {},
          )
          as void Function(_i2.VideoAdPlayer, _i2.VideoAdPlayerCallback));

  @override
  void Function(_i2.VideoAdPlayer, _i2.AdMediaInfo) get stopAd =>
      (super.noSuchMethod(
            Invocation.getter(#stopAd),
            returnValue: (_i2.VideoAdPlayer pigeon_instance, _i2.AdMediaInfo adMediaInfo) {},
            returnValueForMissingStub:
                (_i2.VideoAdPlayer pigeon_instance, _i2.AdMediaInfo adMediaInfo) {},
          )
          as void Function(_i2.VideoAdPlayer, _i2.AdMediaInfo));

  @override
  _i2.PigeonInstanceManager get pigeon_instanceManager =>
      (super.noSuchMethod(
            Invocation.getter(#pigeon_instanceManager),
            returnValue: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
            returnValueForMissingStub: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
          )
          as _i2.PigeonInstanceManager);

  @override
  _i3.Future<void> setVolume(int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setAdProgress(_i2.VideoProgressUpdate? progress) =>
      (super.noSuchMethod(
            Invocation.method(#setAdProgress, [progress]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i2.VideoAdPlayer pigeon_copy() =>
      (super.noSuchMethod(
            Invocation.method(#pigeon_copy, []),
            returnValue: _FakeVideoAdPlayer_3(this, Invocation.method(#pigeon_copy, [])),
            returnValueForMissingStub: _FakeVideoAdPlayer_3(
              this,
              Invocation.method(#pigeon_copy, []),
            ),
          )
          as _i2.VideoAdPlayer);
}

/// A class which mocks [VideoView].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoView extends _i1.Mock implements _i2.VideoView {
  @override
  void Function(_i2.VideoView, _i2.MediaPlayer, int, int) get onError =>
      (super.noSuchMethod(
            Invocation.getter(#onError),
            returnValue:
                (_i2.VideoView pigeon_instance, _i2.MediaPlayer player, int what, int extra) {},
            returnValueForMissingStub:
                (_i2.VideoView pigeon_instance, _i2.MediaPlayer player, int what, int extra) {},
          )
          as void Function(_i2.VideoView, _i2.MediaPlayer, int, int));

  @override
  _i2.PigeonInstanceManager get pigeon_instanceManager =>
      (super.noSuchMethod(
            Invocation.getter(#pigeon_instanceManager),
            returnValue: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
            returnValueForMissingStub: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
          )
          as _i2.PigeonInstanceManager);

  @override
  _i3.Future<void> setVideoUri(String? uri) =>
      (super.noSuchMethod(
            Invocation.method(#setVideoUri, [uri]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getCurrentPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, []),
            returnValue: _i3.Future<int>.value(0),
            returnValueForMissingStub: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> setAudioFocusRequest(_i2.AudioManagerAudioFocus? focusGain) =>
      (super.noSuchMethod(
            Invocation.method(#setAudioFocusRequest, [focusGain]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i2.VideoView pigeon_copy() =>
      (super.noSuchMethod(
            Invocation.method(#pigeon_copy, []),
            returnValue: _FakeVideoView_4(this, Invocation.method(#pigeon_copy, [])),
            returnValueForMissingStub: _FakeVideoView_4(this, Invocation.method(#pigeon_copy, [])),
          )
          as _i2.VideoView);
}

/// A class which mocks [AdError].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdError extends _i1.Mock implements _i2.AdError {
  @override
  _i2.AdErrorCode get errorCode =>
      (super.noSuchMethod(
            Invocation.getter(#errorCode),
            returnValue: _i2.AdErrorCode.adsPlayerWasNotProvided,
            returnValueForMissingStub: _i2.AdErrorCode.adsPlayerWasNotProvided,
          )
          as _i2.AdErrorCode);

  @override
  int get errorCodeNumber =>
      (super.noSuchMethod(
            Invocation.getter(#errorCodeNumber),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i2.AdErrorType get errorType =>
      (super.noSuchMethod(
            Invocation.getter(#errorType),
            returnValue: _i2.AdErrorType.load,
            returnValueForMissingStub: _i2.AdErrorType.load,
          )
          as _i2.AdErrorType);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#message)),
            returnValueForMissingStub: _i4.dummyValue<String>(this, Invocation.getter(#message)),
          )
          as String);

  @override
  _i2.PigeonInstanceManager get pigeon_instanceManager =>
      (super.noSuchMethod(
            Invocation.getter(#pigeon_instanceManager),
            returnValue: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
            returnValueForMissingStub: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
          )
          as _i2.PigeonInstanceManager);

  @override
  _i2.AdError pigeon_copy() =>
      (super.noSuchMethod(
            Invocation.method(#pigeon_copy, []),
            returnValue: _FakeAdError_5(this, Invocation.method(#pigeon_copy, [])),
            returnValueForMissingStub: _FakeAdError_5(this, Invocation.method(#pigeon_copy, [])),
          )
          as _i2.AdError);
}

/// A class which mocks [AdErrorEvent].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdErrorEvent extends _i1.Mock implements _i2.AdErrorEvent {
  @override
  _i2.AdError get error =>
      (super.noSuchMethod(
            Invocation.getter(#error),
            returnValue: _FakeAdError_5(this, Invocation.getter(#error)),
            returnValueForMissingStub: _FakeAdError_5(this, Invocation.getter(#error)),
          )
          as _i2.AdError);

  @override
  _i2.PigeonInstanceManager get pigeon_instanceManager =>
      (super.noSuchMethod(
            Invocation.getter(#pigeon_instanceManager),
            returnValue: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
            returnValueForMissingStub: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
          )
          as _i2.PigeonInstanceManager);

  @override
  _i2.AdErrorEvent pigeon_copy() =>
      (super.noSuchMethod(
            Invocation.method(#pigeon_copy, []),
            returnValue: _FakeAdErrorEvent_6(this, Invocation.method(#pigeon_copy, [])),
            returnValueForMissingStub: _FakeAdErrorEvent_6(
              this,
              Invocation.method(#pigeon_copy, []),
            ),
          )
          as _i2.AdErrorEvent);
}

/// A class which mocks [AdErrorListener].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdErrorListener extends _i1.Mock implements _i2.AdErrorListener {
  @override
  void Function(_i2.AdErrorListener, _i2.AdErrorEvent) get onAdError =>
      (super.noSuchMethod(
            Invocation.getter(#onAdError),
            returnValue: (_i2.AdErrorListener pigeon_instance, _i2.AdErrorEvent event) {},
            returnValueForMissingStub:
                (_i2.AdErrorListener pigeon_instance, _i2.AdErrorEvent event) {},
          )
          as void Function(_i2.AdErrorListener, _i2.AdErrorEvent));

  @override
  _i2.PigeonInstanceManager get pigeon_instanceManager =>
      (super.noSuchMethod(
            Invocation.getter(#pigeon_instanceManager),
            returnValue: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
            returnValueForMissingStub: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
          )
          as _i2.PigeonInstanceManager);

  @override
  _i2.AdErrorListener pigeon_copy() =>
      (super.noSuchMethod(
            Invocation.method(#pigeon_copy, []),
            returnValue: _FakeAdErrorListener_7(this, Invocation.method(#pigeon_copy, [])),
            returnValueForMissingStub: _FakeAdErrorListener_7(
              this,
              Invocation.method(#pigeon_copy, []),
            ),
          )
          as _i2.AdErrorListener);
}

/// A class which mocks [AdEvent].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdEvent extends _i1.Mock implements _i2.AdEvent {
  @override
  _i2.AdEventType get type =>
      (super.noSuchMethod(
            Invocation.getter(#type),
            returnValue: _i2.AdEventType.adBreakEnded,
            returnValueForMissingStub: _i2.AdEventType.adBreakEnded,
          )
          as _i2.AdEventType);

  @override
  _i2.PigeonInstanceManager get pigeon_instanceManager =>
      (super.noSuchMethod(
            Invocation.getter(#pigeon_instanceManager),
            returnValue: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
            returnValueForMissingStub: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
          )
          as _i2.PigeonInstanceManager);

  @override
  _i2.AdEvent pigeon_copy() =>
      (super.noSuchMethod(
            Invocation.method(#pigeon_copy, []),
            returnValue: _FakeAdEvent_8(this, Invocation.method(#pigeon_copy, [])),
            returnValueForMissingStub: _FakeAdEvent_8(this, Invocation.method(#pigeon_copy, [])),
          )
          as _i2.AdEvent);
}

/// A class which mocks [AdEventListener].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdEventListener extends _i1.Mock implements _i2.AdEventListener {
  @override
  void Function(_i2.AdEventListener, _i2.AdEvent) get onAdEvent =>
      (super.noSuchMethod(
            Invocation.getter(#onAdEvent),
            returnValue: (_i2.AdEventListener pigeon_instance, _i2.AdEvent event) {},
            returnValueForMissingStub: (_i2.AdEventListener pigeon_instance, _i2.AdEvent event) {},
          )
          as void Function(_i2.AdEventListener, _i2.AdEvent));

  @override
  _i2.PigeonInstanceManager get pigeon_instanceManager =>
      (super.noSuchMethod(
            Invocation.getter(#pigeon_instanceManager),
            returnValue: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
            returnValueForMissingStub: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
          )
          as _i2.PigeonInstanceManager);

  @override
  _i2.AdEventListener pigeon_copy() =>
      (super.noSuchMethod(
            Invocation.method(#pigeon_copy, []),
            returnValue: _FakeAdEventListener_9(this, Invocation.method(#pigeon_copy, [])),
            returnValueForMissingStub: _FakeAdEventListener_9(
              this,
              Invocation.method(#pigeon_copy, []),
            ),
          )
          as _i2.AdEventListener);
}

/// A class which mocks [AdsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdsManager extends _i1.Mock implements _i2.AdsManager {
  @override
  List<double> get adCuePoints =>
      (super.noSuchMethod(
            Invocation.getter(#adCuePoints),
            returnValue: <double>[],
            returnValueForMissingStub: <double>[],
          )
          as List<double>);

  @override
  _i2.PigeonInstanceManager get pigeon_instanceManager =>
      (super.noSuchMethod(
            Invocation.getter(#pigeon_instanceManager),
            returnValue: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
            returnValueForMissingStub: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
          )
          as _i2.PigeonInstanceManager);

  @override
  _i3.Future<void> discardAdBreak() =>
      (super.noSuchMethod(
            Invocation.method(#discardAdBreak, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> skip() =>
      (super.noSuchMethod(
            Invocation.method(#skip, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i2.AdsManager pigeon_copy() =>
      (super.noSuchMethod(
            Invocation.method(#pigeon_copy, []),
            returnValue: _FakeAdsManager_10(this, Invocation.method(#pigeon_copy, [])),
            returnValueForMissingStub: _FakeAdsManager_10(
              this,
              Invocation.method(#pigeon_copy, []),
            ),
          )
          as _i2.AdsManager);

  @override
  _i3.Future<void> addAdErrorListener(_i2.AdErrorListener? errorListener) =>
      (super.noSuchMethod(
            Invocation.method(#addAdErrorListener, [errorListener]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addAdEventListener(_i2.AdEventListener? adEventListener) =>
      (super.noSuchMethod(
            Invocation.method(#addAdEventListener, [adEventListener]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> destroy() =>
      (super.noSuchMethod(
            Invocation.method(#destroy, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> init(_i2.AdsRenderingSettings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#init, [settings]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> focus() =>
      (super.noSuchMethod(
            Invocation.method(#focus, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.AdProgressInfo?> getAdProgressInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getAdProgressInfo, []),
            returnValue: _i3.Future<_i2.AdProgressInfo?>.value(),
            returnValueForMissingStub: _i3.Future<_i2.AdProgressInfo?>.value(),
          )
          as _i3.Future<_i2.AdProgressInfo?>);

  @override
  _i3.Future<_i2.Ad?> getCurrentAd() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentAd, []),
            returnValue: _i3.Future<_i2.Ad?>.value(),
            returnValueForMissingStub: _i3.Future<_i2.Ad?>.value(),
          )
          as _i3.Future<_i2.Ad?>);

  @override
  _i3.Future<void> removeAdErrorListener(_i2.AdErrorListener? errorListener) =>
      (super.noSuchMethod(
            Invocation.method(#removeAdErrorListener, [errorListener]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeAdEventListener(_i2.AdEventListener? adEventListener) =>
      (super.noSuchMethod(
            Invocation.method(#removeAdEventListener, [adEventListener]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AdsRenderingSettings].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdsRenderingSettings extends _i1.Mock implements _i2.AdsRenderingSettings {
  @override
  _i2.PigeonInstanceManager get pigeon_instanceManager =>
      (super.noSuchMethod(
            Invocation.getter(#pigeon_instanceManager),
            returnValue: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
            returnValueForMissingStub: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
          )
          as _i2.PigeonInstanceManager);

  @override
  _i3.Future<int> getBitrateKbps() =>
      (super.noSuchMethod(
            Invocation.method(#getBitrateKbps, []),
            returnValue: _i3.Future<int>.value(0),
            returnValueForMissingStub: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> getEnableCustomTabs() =>
      (super.noSuchMethod(
            Invocation.method(#getEnableCustomTabs, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> getEnablePreloading() =>
      (super.noSuchMethod(
            Invocation.method(#getEnablePreloading, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> getFocusSkipButtonWhenAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#getFocusSkipButtonWhenAvailable, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<String>?> getMimeTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getMimeTypes, []),
            returnValue: _i3.Future<List<String>?>.value(),
            returnValueForMissingStub: _i3.Future<List<String>?>.value(),
          )
          as _i3.Future<List<String>?>);

  @override
  _i3.Future<void> setBitrateKbps(int? bitrate) =>
      (super.noSuchMethod(
            Invocation.method(#setBitrateKbps, [bitrate]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setEnableCustomTabs(bool? enableCustomTabs) =>
      (super.noSuchMethod(
            Invocation.method(#setEnableCustomTabs, [enableCustomTabs]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setEnablePreloading(bool? enablePreloading) =>
      (super.noSuchMethod(
            Invocation.method(#setEnablePreloading, [enablePreloading]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setFocusSkipButtonWhenAvailable(bool? enableFocusSkipButton) =>
      (super.noSuchMethod(
            Invocation.method(#setFocusSkipButtonWhenAvailable, [enableFocusSkipButton]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setLoadVideoTimeout(int? loadVideoTimeout) =>
      (super.noSuchMethod(
            Invocation.method(#setLoadVideoTimeout, [loadVideoTimeout]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setMimeTypes(List<String>? mimeTypes) =>
      (super.noSuchMethod(
            Invocation.method(#setMimeTypes, [mimeTypes]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setPlayAdsAfterTime(double? time) =>
      (super.noSuchMethod(
            Invocation.method(#setPlayAdsAfterTime, [time]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setUiElements(List<_i2.UiElement>? uiElements) =>
      (super.noSuchMethod(
            Invocation.method(#setUiElements, [uiElements]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i2.AdsRenderingSettings pigeon_copy() =>
      (super.noSuchMethod(
            Invocation.method(#pigeon_copy, []),
            returnValue: _FakeAdsRenderingSettings_11(this, Invocation.method(#pigeon_copy, [])),
            returnValueForMissingStub: _FakeAdsRenderingSettings_11(
              this,
              Invocation.method(#pigeon_copy, []),
            ),
          )
          as _i2.AdsRenderingSettings);
}

/// A class which mocks [ImaSdkFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockImaSdkFactory extends _i1.Mock implements _i2.ImaSdkFactory {
  @override
  _i2.PigeonInstanceManager get pigeon_instanceManager =>
      (super.noSuchMethod(
            Invocation.getter(#pigeon_instanceManager),
            returnValue: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
            returnValueForMissingStub: _FakePigeonInstanceManager_0(
              this,
              Invocation.getter(#pigeon_instanceManager),
            ),
          )
          as _i2.PigeonInstanceManager);

  @override
  _i3.Future<_i2.CompanionAdSlot> createCompanionAdSlot() =>
      (super.noSuchMethod(
            Invocation.method(#createCompanionAdSlot, []),
            returnValue: _i3.Future<_i2.CompanionAdSlot>.value(
              _FakeCompanionAdSlot_12(this, Invocation.method(#createCompanionAdSlot, [])),
            ),
            returnValueForMissingStub: _i3.Future<_i2.CompanionAdSlot>.value(
              _FakeCompanionAdSlot_12(this, Invocation.method(#createCompanionAdSlot, [])),
            ),
          )
          as _i3.Future<_i2.CompanionAdSlot>);

  @override
  _i3.Future<_i2.ImaSdkSettings> createImaSdkSettings() =>
      (super.noSuchMethod(
            Invocation.method(#createImaSdkSettings, []),
            returnValue: _i3.Future<_i2.ImaSdkSettings>.value(
              _FakeImaSdkSettings_13(this, Invocation.method(#createImaSdkSettings, [])),
            ),
            returnValueForMissingStub: _i3.Future<_i2.ImaSdkSettings>.value(
              _FakeImaSdkSettings_13(this, Invocation.method(#createImaSdkSettings, [])),
            ),
          )
          as _i3.Future<_i2.ImaSdkSettings>);

  @override
  _i3.Future<_i2.AdsLoader> createAdsLoader(
    _i2.ImaSdkSettings? settings,
    _i2.AdDisplayContainer? container,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createAdsLoader, [settings, container]),
            returnValue: _i3.Future<_i2.AdsLoader>.value(
              _FakeAdsLoader_14(this, Invocation.method(#createAdsLoader, [settings, container])),
            ),
            returnValueForMissingStub: _i3.Future<_i2.AdsLoader>.value(
              _FakeAdsLoader_14(this, Invocation.method(#createAdsLoader, [settings, container])),
            ),
          )
          as _i3.Future<_i2.AdsLoader>);

  @override
  _i3.Future<_i2.AdsRequest> createAdsRequest() =>
      (super.noSuchMethod(
            Invocation.method(#createAdsRequest, []),
            returnValue: _i3.Future<_i2.AdsRequest>.value(
              _FakeAdsRequest_15(this, Invocation.method(#createAdsRequest, [])),
            ),
            returnValueForMissingStub: _i3.Future<_i2.AdsRequest>.value(
              _FakeAdsRequest_15(this, Invocation.method(#createAdsRequest, [])),
            ),
          )
          as _i3.Future<_i2.AdsRequest>);

  @override
  _i3.Future<_i2.AdsRenderingSettings> createAdsRenderingSettings() =>
      (super.noSuchMethod(
            Invocation.method(#createAdsRenderingSettings, []),
            returnValue: _i3.Future<_i2.AdsRenderingSettings>.value(
              _FakeAdsRenderingSettings_11(
                this,
                Invocation.method(#createAdsRenderingSettings, []),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.AdsRenderingSettings>.value(
              _FakeAdsRenderingSettings_11(
                this,
                Invocation.method(#createAdsRenderingSettings, []),
              ),
            ),
          )
          as _i3.Future<_i2.AdsRenderingSettings>);

  @override
  _i2.ImaSdkFactory pigeon_copy() =>
      (super.noSuchMethod(
            Invocation.method(#pigeon_copy, []),
            returnValue: _FakeImaSdkFactory_16(this, Invocation.method(#pigeon_copy, [])),
            returnValueForMissingStub: _FakeImaSdkFactory_16(
              this,
              Invocation.method(#pigeon_copy, []),
            ),
          )
          as _i2.ImaSdkFactory);
}
